### ISSUE TITLE
[html] рефакторинг-верстка страницы произведения

### ISSUE THREAD

**Issue by Mazian** [FantLab/fantlab_pub#22]
### подготовка:
- [x] #4 - переверстка блока рейтинга (и внедрение)
- [ ] #10 - переверстка блока "книжные полки" для ворка (и внедрение)
- [x] #5 - переверстка классификатора (и внедрение)

### далее:
- [x] - переверстка блока языков произведения
- [x] - переверстка блока заголовка (и постера)
- [ ] - адаптировать открывающейся блок классификации
- [x] #8 - адаптивная переверстка верхнего блока карточки ворка (до дескрипшна включительно)

### полезное:
верстка всего шаблона страницы произведения
http://jsbin.com/midiyus/edit?html,css,output

**Comment by Mazian** [comment]
внедрил!
правда обошелся без рефактинга и перевестки блоков "книжных полок" и открывающегося блока классификатора - там пока всё в таблицах осталось, я только div-обертки сделал и с их помощью это заставил выводиться приемлемо. Пока так.
